### ISSUE TITLE
German umlauts

### ISSUE THREAD

**Issue by mplx** [milosz/greasemonkey-gitlab-scoped-labels#1]
Labels do not get proberly formatted when using extended latin characters as umlauts - they're not catched by regex `\w` (equals to [^A-Za-z0-9_]).

`Priorität::1` renders to 
![Screenshot from 2021-11-29 20-36-01](https://user-images.githubusercontent.com/1986588/143931281-0a58219b-d7e3-46d9-a5f3-2b647e28ecf6.png)

**Comment by milosz** [comment]
updated `\w` to `[^:]` in #2 

does it work for you?

**Comment by mplx** [comment]
Result of the script in `milosz-patch-1` branch:

![Screenshot from 2021-11-30 00-05-11](https://user-images.githubusercontent.com/1986588/143956754-962477ac-14ec-455f-86c7-7a9ff755d3fa.png)

Yes, it works, can be merged! Thank you @milosz 👍🏼

**Comment by milosz** [comment]
Thanks. Have a nice day.
