### ISSUE TITLE
Using your script

### ISSUE THREAD

**Issue by wil-den** [milosz/greasemonkey-gitlab-scoped-labels#4]
Hi,
I was wondering if you tell me how to use your script?
I am not so experienced with gitlab.

Sorry for the dumb question.

Thanks in advance,
Wil

**Comment by milosz** [comment]
Install https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/ in firefox and add js script inside it. Do not forget to update include line (gitlab address).

I will update readme file this week.

Kind regards,
Milosz

**Comment by wil-den** [comment]
Thanks for the prompt reply. 
I am not familiar with greasemonkey but I will be very shortly :)

Thanks again
